const TILE_SIZE = 35;

const EXPLOSION_TIME = 2000;

const SPOIL_CHANCE = 100; // 15
const SPEED = 0;
const POWER = 1;
const DELAY = 2;

const EMPTY_CELL = 0;
const DESTRUCTIBLE_CELL = 2;
const NON_DESTRUCTIBLE_CELL = 1;

const INITIAL_POWER = 1
const STEP_POWER = 1

module.exports = {
  TILE_SIZE,
  EXPLOSION_TIME,
  SPOIL_CHANCE,
  SPEED,
  POWER,
  DELAY,
  EMPTY_CELL,
  DESTRUCTIBLE_CELL,
  NON_DESTRUCTIBLE_CELL,
  INITIAL_POWER,
  STEP_POWER
}
